Grails2.3/Test: revert adding IntegrationTestMixin
It breaks integration tests with the new Spock interface with:

java.lang.IllegalStateException: Cannot activate transaction synchronization - already active